### ISSUE TITLE
Replace "prettier" package

### ISSUE THREAD

**Issue by WillianGoncalves** [concordialang/ui-core#5]
Replace `prettier` package with other formatter package.
According to @thiagodp, the `prettier` package currently has few options for formatting the code produced. It has been tested and is not worth keeping.

**Comment by thiagodp** [comment]
Yep, projects such as [typescript-formatter](https://github.com/vvakame/typescript-formatter) offer more options to customize code, although being less popular. Since it may take a while to analyze them, I suggest that we postpone this choice.

**Comment by thiagodp** [comment]
Adopting `tslint` + `prettier` for now...
